include ..\make.rules

kernel:

# Call to PASCALMAIN is within kernel file.

	$(NASM) $(NASMOPT)   -o obj\prt0.o prt0.asm 
	$(FPC) $(FPCOPT)    -Fu..\rtl\units\i386-coffee -Fuobj -FUobj -o..\iso\boot\coffee kernel

# --gc-sections -s cuts RTTI out of binary file.
	ld --gc-sections -s -T linker.ld -o..\iso\boot\coffee

# ld output is coffee(in ELF format)


clean:
	erase .\obj\*.*
