include ../make.rules
all:
	make -C coffee
	make -C i386
	make -C objpas
#	make -C inc
#	make -C TV
	
clean:
	erase .\units\i386-coffee\*.ppu
	erase .\units\i386-coffee\*.o
	erase .\units\i386-coffee\*.a
	erase .\units\i386-coffee\*.rst