
{*******************************************************}
{                                                       }
{       Borland Pascal Version 7.0                      }
{       Turbo Vision Build Program                      }
{                                                       }
{       Copyright (c) 1992 Borland International        }
{                                                       }
{*******************************************************}

program Build;

uses
  Strings,
  Objects,
  Drivers,
  Memory,
  Views,
  Menus,
  Dialogs,
  StdDlg,
  MsgBox,
  TextView,
  Colorsel,
  Editors,
  App,
  Validate,
  Outline;

begin
end.
